name: Ansible Deploy to AWS

on:
  push:
  workflow_dispatch:

jobs:
  ansible01:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Source Code
      uses: actions/checkout@v2.4.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Build Ansible Inventory from Amazon EC2
      run: |
        pip3 install boto3
        ansible-galaxy collection install amazon.aws
        ansible-inventory --inventory inventory.aws_ec2.yml --list -vvvv
